function initialize()
    src.gui.variables.app();

    lamp_struct = struct( ...
        'npal', 'visualize_lightLamp', ...
        'binaries', 'BinariesLamp', ...
        'dependencies', 'DependenciesLamp', ...
        'runtime', 'MatlabRuntimeLamp_2', ...
        'models', 'ModelsLamp', ...
        'namespaces', 'NamespacesLamp');
    set(src.gui.variables.lamps, lamp_struct);
end

